import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from "react"

export default function Home() {
  const [num, setNum] = useState(0)
  function minus(){
    setNum(num-1)
  }
  function plus(){
    setNum(num+1)
  }
  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1>{num}</h1>
        <button onClick={plus}>+</button>
        <button onClick={minus}>-</button>
      </div>
  )
}